project:
  type: website

website:
  title: "Bayesian Inference and Functional Programming"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jonnylaw
      - icon: twitter
        href: https://twitter.com/lawsy
format:
  html:
    theme: litera
    css: styles.css

site-url: https://jonnylaw.rocks