---
title: "About Me"
description: |
  About the author.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Jonny Law is a data scientist at the [National Innovation Centre for Data](https://www.ncl.ac.uk/nicd/), working with local and national companies to allow them to make the most of their data. Previously he was a Statistics PhD student on the [Cloud Computing for Big Data CDT](http://www.bigdata-cdt.ac.uk/). His primary research interest is in using functional programming for Bayesian Inference using [Scala](http://www.scala-lang.org/).

## Skills

* R
* Scala
* Python
* SQL
* Bayesian Statistics
* Time series analysis
* Machine Learning

## Projects

**Bayesian State Space Model**

[git.io/dlm](https://jonnylaw.github.io/bayesian_dlms/) 
*A Scala library for Dynamic Linear Models, with filtering and parameter inference algorithms*

**Gaussian Processes**

[git.io/gaussianprocesses](https://jonnylaw.github.io/gaussian-processes/)
*A Scala library for Gaussian Processes*

**Composable POMP Models**

[git.io/statespace](https://git.io/statespace) 
*A Scala library for online Bayesian filtering of univariate state space models, sometimes called POMP (Partially Observed Markov Process Models).*