graph TD                                                                    
    A((Person)) -->|Speaks At| B((Conference))
    A -->|Works At| C((Company))
    A -->|Lives In| D((City))
    B -->|Hosted In| D

style A fill:#018bff,stroke-width:0,color:#fff  
style B fill:#ff8e6a,stroke-width:0,color:#fff 
style C fill:#ff8e6a,stroke-width:0,color:#fff
style D fill:#018bff,stroke-width:0,color:#fff