graph LR
    J(("Jonny Law"))

    NU(("Newcastle\nUniversity"))
    PHD(("Statistics\nPhD"))

    Neo((Neo4j))

    FP((Functional <br /> Programming))

    J -->|Studied At| NU
    J -->|Works At| Neo
    NU -->|Awarded| PHD
    J -->|Loves| FP

style J fill:#4bc994,stroke-width:0,color:#fff  
style NU fill:#ff8e6a,stroke-width:0,color:#fff 
style PHD fill:#018bff,stroke-width:0,color:#fff
style Neo fill:#018bff,stroke-width:0,color:#fff
style FP fill:#ff8e6a,stroke-width:0,color:#fff