name: Publish Blog

on:
  push:
    branches: [ main, build-in-ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -t blog-build .
    - name: Render site
      run: docker run --rm -v "$(pwd)":/home/rstudio/project -w /home/rstudio/project blog-build bash -c "quarto render"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: quarto-site
          path: _site
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

