name: Publish Blog

on:
  push:
    branches: [ main, fix-rendering ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Blog
      run: ./build.sh

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
